### ISSUE TITLE
ErrorFilter demo

### ISSUE THREAD

**Issue by helio-frota** [nodeshift-starters/opossum-playground#39]
The idea is to create a demo using errorFilter feature.

We can use the same client-server example and when the client try to access a 404 URL the errorFilter should ignore that failure.

We don't need lowcarb for this and don't need to point to debug branch.

**Comment by aalykiot** [comment]
related to: https://stackoverflow.com/questions/64385301/ignore-http-404-error-in-opossum-circuitbreaker

**Comment by helio-frota** [comment]
really good demo 
merged https://github.com/nodeshift-starters/opossum-playground/pull/40
